Miw\DemoBundle\Entity\Personal:
    type: entity
    table: personal
    uniqueConstraints:
        dni:
            columns:
                - dni
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dni:
            type: integer
            nullable: true
            options:
                unsigned: false
        nombre:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        contador:
            type: integer
            nullable: true
            options:
                unsigned: false
    lifecycleCallbacks: {  }
