Miw\DemoBundle\Entity\Producto:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 255
        precio:
            type: float
        descripcion:
            type: string
            length: 255
    lifecycleCallbacks: {  }
